#!/usr/bin/env python

from glob import glob

div_stack = 0
flag = False

for f in glob("./*"):
  if ".html" in f:
    lines = [l.strip("\n") for l in open(f,"r")]
    file = []
    for l in lines:
      if "</div>" in l and flag:
        div_stack -= 1
        flag = (div_stack !=0)
        continue
      elif "<div" in l and flag:
        div_stack += 1
        continue
      elif flag:
        continue


      if '<div class="header">' in l:
        div_stack = 1
        l = "<?php include($_SERVER['DOCUMENT_ROOT'] . '/assets/header.php') ?>"
        flag = True
      
      elif '<div class="nav-menu">' in l:
        div_stack = 1
        l = "<?php include($_SERVER['DOCUMENT_ROOT'] . '/assets/nav-menu.php') ?>"
        flag = True

      elif '<div class="contact-info">' in l:
        div_stack = 1
        l = "<?php include($_SERVER['DOCUMENT_ROOT'] . '/assets/contact.php') ?>"
        flag = True
        
      file.append(l)
    f = f.strip("./html") + ".php"
    wr = open(f,"w")
    [wr.write(l+"\n") for l in file]
    wr.close()  
